services:
  app:
    image: node:22.12.0-alpine
    platform: linux/arm64/v8
    ports:
      - "3000:3000"
    volumes:
      - .:/home/node/app
      - node_modules:/home/node/app/node_modules
    working_dir: /home/node/app/
    command: sh -c "npm i -g pnpm@10.7.0 && pnpm install && pnpm dev"
    depends_on:
      - db
    environment:
      - NODE_ENV=development
      - DATABASE_URI=postgres://payload:secret@db:5432/payload-playground
    env_file:
      - .env

  db:
    image: postgres:16.8
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: payload
      POSTGRES_PASSWORD: secret
      POSTGRES_DB: payload-playground
    volumes:
      - data:/var/lib/postgresql/data
    logging:
      driver: none

volumes:
  data:
  node_modules:
